import js from '@eslint/js';
import tseslint from 'typescript-eslint';

/**
 * SANA's lint rules.
 *
 * Beyond the usual hygiene, two rules exist to hold safety decisions that are
 * otherwise only written down in prose. Documents do not stop a contributor in
 * a hurry six days before a demo; a failing build does.
 */
export default tseslint.config(
  {
    ignores: [
      'node_modules/',
      'dist/',
      'coverage/',
      // Generated by tools/extract_tokens.py and verified byte-exactly by
      // `npm run tokens:check`. Linting it would only invite hand-edits.
      'packages/tokens/src/',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': 'off',
    },
  },

  {
    // The web app must contain no contextual data as literals. Decision 0003:
    // the emergency number, the site, the hospital and the safety officer are
    // stored and read at runtime. A wrong emergency number is worse than a
    // missing one, and a literal is how a wrong one survives into production.
    files: ['apps/web/src/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector:
            "Literal[value=/(^|\\D)(999|911|112|998|000|1-1-2|9-1-1)(\\D|$)/]",
          message:
            'Emergency numbers are contextual data, never literals (docs/decisions/0003-no-seeded-data.md). ' +
            'Read it from the context store; if it is absent, show the unconfigured state rather than a default.',
        },
      ],
    },
  },

  {
    // Test files reach into content on disk and assert on malformed input, so
    // they legitimately need shapes the type system would otherwise reject.
    files: ['**/*.test.ts', '**/*.test.tsx'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
);
